# Generated by Django 3.1.3 on 2020-12-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201202_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist_items',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist_items',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
        migrations.DeleteModel(
            name='WishList_items',
        ),
    ]
