# Generated by Django 3.1 on 2021-01-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_country_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='phone',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='pincode',
            field=models.CharField(default='none', max_length=6),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='address',
            field=models.CharField(default='none', max_length=2000),
        ),
    ]
